image: node:10
stages:
  - check
  - test
  - cov

variables:
  DOCKER_DRIVER: overlay2

# Cache modules in between jobs
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#   - yarn-cache/

before_script:
  # - yarn config set cache-folder .yarn-cache
  - npm ci -q

check:
  stage: check
  script:
  - npm run lint
  # - npm run dep-check
  - npm install --no-lockfile @commitlint/config-conventional @commitlint/cli --save-dev
  - npx commitlint --extends=@commitlint/config-conventional --from=$CI_COMMIT_BEFORE_SHA --to=$CI_COMMIT_SHA

test-node-8:
  stage: test
  image: node:8
  script:
    - COVERAGE=TRUE npx nyc -s npm run test:node
  artifacts:
    paths:
      - .nyc_output/

test-node-10:
  stage: test
  script:
    - COVERAGE=TRUE npx nyc -s npm run test:node
  artifacts:
    paths:
      - .nyc_output/

test-browser-chrome:
  image: hugomrdias/node-chrome:test
  stage: test
  script:
    - AEGIR_BROWSERS=ChromeDocker npm run test:browser
  artifacts:
    reports:
      junit: junit-report-*.xml

test-browser-firefox:
  image: hugomrdias/node-firefox:test
  stage: test
  script:
    - cd node_modules/aegir
    - npm i --save-dev karma-coverage-istanbul-reporter
    - cd ../..
    - AEGIR_BROWSERS=FirefoxHeadless npm run test:browser
  artifacts:
    paths:
      - coverage/
    reports:
      junit: junit-report-*.xml

cov:
  stage: cov
  script: 
    - ls -al
    - npx nyc report --reporter text-summary --reporter html
  dependencies:
    - test-node-10
  artifacts:
    paths:
      - coverage/
  coverage: '/Lines        : \d+\.\d+/'

cov2:
  stage: cov
  script: 
    - ls -al
    - npx nyc report --reporter text-summary --reporter html
  dependencies:
    - test-node-10
    - test-node-8
  artifacts:
    paths:
      - coverage/
      - .nyc_output/
  coverage: '/Lines        : \d+\.\d+/'